# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: native

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
          cache: maven
          native-image-job-reports: 'true'
      - name: Build with Maven
        run: |
          version=$(cat pom.xml | grep -oPm1 '(?<=<version>).*?(?=</version>)')
          echo "version=v$version" >> $GITHUB_ENV
          bash ./native-package.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.version }}
          body_path: UPDATE.md
          tag_name: ${{ env.version }}
          append_body: false
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ./target/ani-rss
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./docker/Dockerfile-native.tpl
          push: true
          tags: wushuo894/ani-rss-native:latest
      - name: DockerHub Description
        uses: peter-evans/dockerhub-description@v4.0.0
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERHUB_REPOSITORY: wushuo894/ani-rss-native
          README_FILEPATH: ./DOCKER.md